/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepertoriosRouteImport } from './routes/repertorios'
import { Route as PresencaRouteImport } from './routes/presenca'
import { Route as MusicasRouteImport } from './routes/musicas'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const RepertoriosRoute = RepertoriosRouteImport.update({
  id: '/repertorios',
  path: '/repertorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PresencaRoute = PresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasRoute = MusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/membros': typeof MembrosRoute
  '/musicas': typeof MusicasRoute
  '/presenca': typeof PresencaRoute
  '/repertorios': typeof RepertoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/membros': typeof MembrosRoute
  '/musicas': typeof MusicasRoute
  '/presenca': typeof PresencaRoute
  '/repertorios': typeof RepertoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/membros': typeof MembrosRoute
  '/musicas': typeof MusicasRoute
  '/presenca': typeof PresencaRoute
  '/repertorios': typeof RepertoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/membros'
    | '/musicas'
    | '/presenca'
    | '/repertorios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agenda' | '/membros' | '/musicas' | '/presenca' | '/repertorios'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/membros'
    | '/musicas'
    | '/presenca'
    | '/repertorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  MembrosRoute: typeof MembrosRoute
  MusicasRoute: typeof MusicasRoute
  PresencaRoute: typeof PresencaRoute
  RepertoriosRoute: typeof RepertoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repertorios': {
      id: '/repertorios'
      path: '/repertorios'
      fullPath: '/repertorios'
      preLoaderRoute: typeof RepertoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presenca': {
      id: '/presenca'
      path: '/presenca'
      fullPath: '/presenca'
      preLoaderRoute: typeof PresencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas': {
      id: '/musicas'
      path: '/musicas'
      fullPath: '/musicas'
      preLoaderRoute: typeof MusicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  MembrosRoute: MembrosRoute,
  MusicasRoute: MusicasRoute,
  PresencaRoute: PresencaRoute,
  RepertoriosRoute: RepertoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
